// Autogenerated from KST: please remove this line if doing any edits by hand!

package if_values

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestIfValues(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r IfValues
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 80, r.Codes()[0].Opcode())
	assert.EqualValues(t, 40, r.Codes()[0].HalfOpcode())
	assert.EqualValues(t, 65, r.Codes()[1].Opcode())
	assert.Nil(t, r.Codes()[1].HalfOpcode())
	assert.EqualValues(t, 67, r.Codes()[2].Opcode())
	assert.Nil(t, r.Codes()[2].HalfOpcode())
}
