// Autogenerated from KST: please remove this line if doing any edits by hand!

package if_values

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestIfValues(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r IfValues
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	codes := r.Codes()
	assert.EqualValues(t, 80, codes[0].Opcode())
	assert.EqualValues(t, 40, codes[0].HalfOpcode())
	assert.EqualValues(t, 65, codes[1].Opcode())
	// assert.Nil(t, codes[1].HalfOpcode()) uint cannot be nil
	assert.EqualValues(t, 0, codes[1].HalfOpcode())
	assert.EqualValues(t, 67, codes[2].Opcode())
	// assert.Nil(t, codes[2].HalfOpcode()) uint cannot be nil
	assert.EqualValues(t, 0, codes[2].HalfOpcode())
}
