// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestExprArray(t *testing.T) {
	f, err := os.Open("../../src/expr_array.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r ExprArray
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	tmp1, err := r.AintSize()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 4, tmp1)
	tmp2, err := r.AintFirst()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 7657765, tmp2)
	tmp3, err := r.AintLast()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 16272640, tmp3)
	tmp4, err := r.AintMin()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 49185, tmp4)
	tmp5, err := r.AintMax()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1123362332, tmp5)
	tmp6, err := r.AfloatSize()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 3, tmp6)
	tmp7, err := r.AfloatFirst()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -2.6839530254859364E-121, tmp7)
	tmp8, err := r.AfloatLast()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -1.1103359815095273E-175, tmp8)
	tmp9, err := r.AfloatMin()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -8.754689149998834E+288, tmp9)
	tmp10, err := r.AfloatMax()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -1.1103359815095273E-175, tmp10)
	tmp11, err := r.AstrSize()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 3, tmp11)
	tmp12, err := r.AstrFirst()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "foo", tmp12)
	tmp13, err := r.AstrLast()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "baz", tmp13)
	tmp14, err := r.AstrMin()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "bar", tmp14)
	tmp15, err := r.AstrMax()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "foo", tmp15)
}
