// Autogenerated from KST: please remove this line if doing any edits by hand!

package expr_array

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExprArray(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/expr_array.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r ExprArray
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 4, r.AintSize())
	assert.EqualValues(t, 7657765, r.AintFirst())
	assert.EqualValues(t, 16272640, r.AintLast())
	assert.EqualValues(t, 49185, r.AintMin())
	assert.EqualValues(t, 1123362332, r.AintMax())
	assert.EqualValues(t, 3, r.AfloatSize())
	assert.EqualValues(t, -2.6839530254859364E-121, r.AfloatFirst())
	assert.EqualValues(t, -1.1103359815095273E-175, r.AfloatLast())
	assert.EqualValues(t, -8.754689149998834E+288, r.AfloatMin())
	assert.EqualValues(t, -1.1103359815095273E-175, r.AfloatMax())
	assert.EqualValues(t, 3, r.AstrSize())
	assert.EqualValues(t, "foo", r.AstrFirst())
	assert.EqualValues(t, "baz", r.AstrLast())
	assert.EqualValues(t, "bar", r.AstrMin())
	assert.EqualValues(t, "foo", r.AstrMax())
}
