// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestInstanceStdArray(t *testing.T) {
	f, err := os.Open("../../src/instance_std_array.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r InstanceStdArray
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 16, r.Ofs)
	assert.EqualValues(t, 3, r.QtyEntries)
	assert.EqualValues(t, 4, r.EntrySize)
	tmp1, err := r.Entries()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 3, len(tmp1))
	tmp2, err := r.Entries()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, []uint8{17, 17, 17, 17}, tmp2[0])
	tmp3, err := r.Entries()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, []uint8{34, 34, 34, 34}, tmp3[1])
	tmp4, err := r.Entries()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, []uint8{51, 51, 51, 51}, tmp4[2])
}
