// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestPositionAbs(t *testing.T) {
	f, err := os.Open("../../src/position_abs.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r PositionAbs
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 32, r.IndexOffset)
	tmp1, err := r.Index()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "foo", tmp1.Entry)
}
