// Autogenerated from KST: please remove this line if doing any edits by hand!

package term_bytes

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTermBytes(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/term_strz.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r TermBytes
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, "\x66\x6F\x6F", r.S1())
	assert.EqualValues(t, "\x62\x61\x72", r.S2())
	assert.EqualValues(t, "\x7C\x62\x61\x7A\x40", r.S3())
}
