// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestFloatToI(t *testing.T) {
	f, err := os.Open("../../src/floating_points.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r FloatToI
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 0.5, r.SingleValue)
	assert.EqualValues(t, 0.25, r.DoubleValue)
	tmp1, err := r.SingleI()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 0, tmp1)
	tmp2, err := r.DoubleI()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 0, tmp2)
	tmp3, err := r.Float1I()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1, tmp3)
	tmp4, err := r.Float2I()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1, tmp4)
	tmp5, err := r.Float3I()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1, tmp5)
	tmp6, err := r.Float4I()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -2, tmp6)
}
