image: golang

stages:
  - unittest
  - build
  - test

before_script:
  - mkdir -p /go/src/gitlab.com/dfir/binary /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/dfir/binary/kaitaigo
  - ln -s /go/src/gitlab.com/dfir/binary /go/src/_/builds/cugu
  - make dep

test:
  stage: unittest
  script: make test

lint:
  stage: unittest
  script: make lint
  allow_failure: true

build:
  stage: build
  script: make build
  artifacts:
    paths:
      - kaitaigo

ks_tests:
  stage: test
  script:
    - ./kaitaigo `find /go/src/gitlab.com/dfir/binary/kaitaigo/tests -name "*.ksy" -type f | grep -v "/enum_fancy/"`
    - make ks_tests
