trigger:
- master

strategy:
  matrix:
    linux:
      imageName: ubuntu-16.04
    mac:
      imageName: macos-10.13
    windows:
      imageName: windows-2019

pool:
  vmImage: $(imageName)

variables:
  GO111MODULE: "on"

steps:
- script: go get github.com/ory/go-acc
  displayName: 'Install go-acc Coverage'
  condition: eq( variables['Agent.OS'], 'Linux' )

- script: |
    go-acc ./...
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Coverage'
  continueOnError: true
  condition: eq( variables['Agent.OS'], 'Linux' )

- script: |
    go test -v ./...
  displayName: 'Test'

- script: go build .
  displayName: 'Build'

- bash: |
    ./kaitaigo `find ./tests -name "*.ksy" -type f | grep -v "/enum_fancy/"`
    make ks_tests
  displayName: 'Run kaitai test suite'
