// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNavParent(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/nav.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r NavParent
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 2, r.Header.QtyEntries)
	assert.EqualValues(t, 8, r.Header.FilenameLen)
	assert.EqualValues(t, 2, len(r.Index.Entries))
	assert.EqualValues(t, "FIRST___", r.Index.Entries[0].Filename)
	assert.EqualValues(t, "SECOND__", r.Index.Entries[1].Filename)
}
