// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestFixedStruct(t *testing.T) {
	f, err := os.Open("../../src/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r FixedStruct
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	tmp1, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 255, tmp1.Uint8)
	tmp2, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 65535, tmp2.Uint16)
	tmp3, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, uint32(4294967295), tmp3.Uint32)
	tmp4, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, uint64(18446744073709551615), tmp4.Uint64)
	tmp5, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -1, tmp5.Sint8)
	tmp6, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -1, tmp6.Sint16)
	tmp7, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -1, tmp7.Sint32)
	tmp8, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -1, tmp8.Sint64)
	tmp9, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 66, tmp9.Uint16le)
	tmp10, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 66, tmp10.Uint32le)
	tmp11, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 66, tmp11.Uint64le)
	tmp12, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -66, tmp12.Sint16le)
	tmp13, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -66, tmp13.Sint32le)
	tmp14, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -66, tmp14.Sint64le)
	tmp15, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 66, tmp15.Uint16be)
	tmp16, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 66, tmp16.Uint32be)
	tmp17, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 66, tmp17.Uint64be)
	tmp18, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -66, tmp18.Sint16be)
	tmp19, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -66, tmp19.Sint32be)
	tmp20, err := r.Hdr()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, -66, tmp20.Sint64be)
}
