// Autogenerated from KST: please remove this line if doing any edits by hand!

package type_ternary

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTypeTernary(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/term_strz.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r TypeTernary
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	tmp1 := r.Dif()
	assert.EqualValues(t, 101, tmp1.Value())
}
