// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNestedSameName(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/repeat_n_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r NestedSameName
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 2, r.MainData.MainSize)
	assert.EqualValues(t, []uint8{16, 0, 0, 0}, r.MainData.Foo.Data)
}
