// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestNestedSameName(t *testing.T) {
	f, err := os.Open("../../src/repeat_n_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r NestedSameName
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 2, r.MainData.MainSize)
	assert.EqualValues(t, []uint8{16, 0, 0, 0}, r.MainData.Foo.Data)
}
