// Autogenerated from KST: please remove this line if doing any edits by hand!

package instance_std

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestInstanceStd(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/str_encodings.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r InstanceStd
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, "Some ", r.Header())
}
