// Autogenerated from KST: please remove this line if doing any edits by hand!

package expr_mod

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExprMod(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r ExprMod
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 1262698832, r.IntU())
	assert.EqualValues(t, -52947, r.IntS())
	assert.EqualValues(t, 9, r.ModPosConst())
	assert.EqualValues(t, 4, r.ModNegConst())
	assert.EqualValues(t, 5, r.ModPosSeq())
	assert.EqualValues(t, 2, r.ModNegSeq())
}
