// Autogenerated from KST: please remove this line if doing any edits by hand!

package nav_parent_vs_value_inst

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNavParentVsValueInst(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/term_strz.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r NavParentVsValueInst
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, "foo", r.S1())
}
