// Autogenerated from KST: please remove this line if doing any edits by hand!

package js_signed_right_shift

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestJsSignedRightShift(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r JsSignedRightShift
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 1073741824, r.ShouldBe40000000())
	assert.EqualValues(t, 10485760, r.ShouldBeA00000())
}
