// Autogenerated from KST: please remove this line if doing any edits by hand!

package expr_bytes_cmp

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExprBytesCmp(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r ExprBytesCmp
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, []uint8{80}, r.One())
	assert.EqualValues(t, []uint8{65, 67, 75}, r.Two())
	assert.EqualValues(t, true, r.IsEq())
	assert.EqualValues(t, false, r.IsNe())
	assert.EqualValues(t, true, r.IsLt())
	assert.EqualValues(t, false, r.IsGt())
	assert.EqualValues(t, true, r.IsLe())
	assert.EqualValues(t, false, r.IsGe())
	assert.EqualValues(t, false, r.IsLt2())
	assert.EqualValues(t, true, r.IsGt2())
}
