// Autogenerated from KST: please remove this line if doing any edits by hand!

package position_to_end

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestPositionToEnd(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/position_to_end.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r PositionToEnd
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 66, r.Index().Foo())
	assert.EqualValues(t, 4660, r.Index().Bar())
}
