// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestNestedTypes3(t *testing.T) {
	f, err := os.Open("../../src/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r NestedTypes3
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 80, r.ACc.ValueCc)
	assert.EqualValues(t, 65, r.ACD.ValueD)
	assert.EqualValues(t, 67, r.B.ValueB)
	assert.EqualValues(t, 75, r.B.ACc.ValueCc)
	assert.EqualValues(t, 45, r.B.ACD.ValueD)
}
