// Autogenerated from KST: please remove this line if doing any edits by hand!

package nested_types3

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestNestedTypes3(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r NestedTypes3
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 80, r.ACc().ValueCc())
	assert.EqualValues(t, 65, r.ACD().ValueD())
	assert.EqualValues(t, 67, r.B().ValueB())
	assert.EqualValues(t, 75, r.B().ACc().ValueCc())
	assert.EqualValues(t, 45, r.B().ACD().ValueD())
}
