// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestProcessCoerceBytes(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/process_coerce_bytes.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r ProcessCoerceBytes
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 0, r.Records[0].Flag)
	tmp1, err := r.Records[0].Buf()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, []uint8{65, 65, 65, 65}, tmp1)
	assert.EqualValues(t, 1, r.Records[1].Flag)
	tmp2, err := r.Records[1].Buf()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, []uint8{66, 66, 66, 66}, tmp2)
}
