// Autogenerated from KST: please remove this line if doing any edits by hand!

package process_rotate

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestProcessRotate(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/process_rotate.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r ProcessRotate
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, []uint8{72, 101, 108, 108, 111}, r.Buf1())
	assert.EqualValues(t, []uint8{87, 111, 114, 108, 100}, r.Buf2())
	assert.EqualValues(t, []uint8{84, 104, 101, 114, 101}, r.Buf3())
}
