// Autogenerated from KST: please remove this line if doing any edits by hand!

package if_struct

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestIfStruct(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/if_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r IfStruct
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 83, r.Op1().Opcode())
	assert.EqualValues(t, "foo", r.Op1().ArgStr().Str())
	assert.EqualValues(t, 84, r.Op2().Opcode())
	assert.EqualValues(t, 66, r.Op2().ArgTuple().Num1())
	assert.EqualValues(t, 67, r.Op2().ArgTuple().Num2())
	assert.EqualValues(t, 83, r.Op3().Opcode())
	assert.EqualValues(t, "bar", r.Op3().ArgStr().Str())
}
