// Autogenerated from KST: please remove this line if doing any edits by hand!

package process_to_user

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestProcessToUser(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/process_rotate.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r ProcessToUser
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, "Hello", r.Buf1().Str())
}
