// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"

	"testing"
)

func TestMetaXref(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r MetaXref
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

}
