// Autogenerated from KST: please remove this line if doing any edits by hand!

package expr_3

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestExpr3(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r Expr3
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 80, r.One())
	assert.EqualValues(t, "ACK", r.Two())
	assert.EqualValues(t, "@ACK", r.Three())
	assert.EqualValues(t, "_ACK_", r.Four())
	assert.EqualValues(t, true, r.IsStrEq())
	assert.EqualValues(t, false, r.IsStrNe())
	assert.EqualValues(t, true, r.IsStrLt())
	assert.EqualValues(t, false, r.IsStrGt())
	assert.EqualValues(t, true, r.IsStrLe())
	assert.EqualValues(t, false, r.IsStrGe())
	assert.EqualValues(t, true, r.IsStrLt2())
	assert.EqualValues(t, true, r.TestNot())
}
