// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestExpr3(t *testing.T) {
	f, err := os.Open("../../src/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r Expr3
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 80, r.One)
	assert.EqualValues(t, "ACK", r.Two)
	tmp1, err := r.Three()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "@ACK", tmp1)
	tmp2, err := r.Four()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, "_ACK_", tmp2)
	tmp3, err := r.IsStrEq()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp3)
	tmp4, err := r.IsStrNe()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp4)
	tmp5, err := r.IsStrLt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp5)
	tmp6, err := r.IsStrGt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp6)
	tmp7, err := r.IsStrLe()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp7)
	tmp8, err := r.IsStrGe()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp8)
	tmp9, err := r.IsStrLt2()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp9)
	tmp10, err := r.TestNot()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp10)
}
