// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestMultipleUse(t *testing.T) {
	f, err := os.Open("../../src/position_abs.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r MultipleUse
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 32, r.T1.FirstUse.Value)
	tmp1, err := r.T2.SecondUse()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 32, tmp1.Value)
}
