// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
	"github.com/stretchr/testify/assert"
)

func TestExprBytesCmp(t *testing.T) {
	f, err := os.Open("../../src/fixed_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r ExprBytesCmp
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, []uint8{80}, r.One)
	assert.EqualValues(t, []uint8{65, 67, 75}, r.Two)
	tmp1, err := r.IsEq()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp1)
	tmp2, err := r.IsNe()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp2)
	tmp3, err := r.IsLt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp3)
	tmp4, err := r.IsGt()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp4)
	tmp5, err := r.IsLe()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp5)
	tmp6, err := r.IsGe()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp6)
	tmp7, err := r.IsLt2()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, false, tmp7)
	tmp8, err := r.IsGt2()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, true, tmp8)
}
