// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestProcessRotate(t *testing.T) {
	f, err := os.Open("../../src/process_rotate.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r ProcessRotate
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, []uint8{72, 101, 108, 108, 111}, r.Buf1)
	assert.EqualValues(t, []uint8{87, 111, 114, 108, 100}, r.Buf2)
	assert.EqualValues(t, []uint8{84, 104, 101, 114, 101}, r.Buf3)
}
