// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"
	"testing"
	"github.com/stretchr/testify/assert"
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	. "test_formats"
)

func TestRepeatNStruct(t *testing.T) {
	f, err := os.Open("../../src/repeat_n_struct.bin")
	if err != nil {
		t.Fatal(err)
	}
	s := kaitai.NewStream(f)
	var r RepeatNStruct
	err = r.Read(s, &r, &r)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 2, len(r.Chunks))
	assert.EqualValues(t, 16, r.Chunks[0].Offset)
	assert.EqualValues(t, 8312, r.Chunks[0].Len)
	assert.EqualValues(t, 8328, r.Chunks[1].Offset)
	assert.EqualValues(t, 15, r.Chunks[1].Len)
}
