// Autogenerated from KST: please remove this line if doing any edits by hand!

package spec

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestProcessCoerceUsertype2(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/process_coerce_bytes.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r ProcessCoerceUsertype2
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, 0, r.Records[0].Flag)
	tmp1, err := r.Records[0].Buf()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1094795585, tmp1.Value)
	assert.EqualValues(t, 1, r.Records[1].Flag)
	tmp2, err := r.Records[1].Buf()
	if err != nil {
		t.Fatal(err)
	}
	assert.EqualValues(t, 1111638594, tmp2.Value)
}
