// Autogenerated from KST: please remove this line if doing any edits by hand!

package str_eos

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestStrEos(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/term_strz.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r StrEos
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, "foo|bar|baz@", r.Str())
}
