// Autogenerated from KST: please remove this line if doing any edits by hand!

package term_strz

import (
	"os"

	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTermStrz(t *testing.T) {
	f, err := os.Open("../../../testdata/kaitai/term_strz.bin")
	if err != nil {
		t.Fatal(err)
	}

	var r TermStrz
	err = r.Decode(f)
	if err != nil {
		t.Fatal(err)
	}

	assert.EqualValues(t, "foo", r.S1())
	assert.EqualValues(t, "bar", r.S2())
	assert.EqualValues(t, "|baz@", r.S3())
}
